#!/bin/bash

echo "Pushing the latest version of the template out to S3..."
aws --region us-east-1 s3api put-object \
    --bucket bali-nebula-environment-us-east-1 \
    --key templates/buckets.json \
    --content-type "application/json" \
    --body ./templates/buckets.json
echo

echo "Updating the cloudformation stack..."
aws --region us-west-2 cloudformation create-stack \
    --stack-name bali-nebula-buckets-us-east-1 \
    --template-url https://s3.amazonaws.com/bali-nebula-environment-us-east-1/templates/buckets.json 
echo

echo "Done."
