#!/bin/bash
SCRIPTS=`dirname $0`

echo
echo "Creating the environment bucket..."
aws --region us-east-1 s3api create-bucket \
    --acl private \
    --bucket craterdog-bali-environment-us-east-1

echo
echo "Pushing the latest version of the template out to S3..."
aws --region us-east-1 s3api put-object \
    --bucket craterdog-bali-environment-us-east-1 \
    --key templates/bali-nebula-environment.json \
    --body templates/bali-nebula-environment.json

echo
echo "Creating the cloudformation stack..."
aws --region us-east-1 cloudformation create-stack \
    --capabilities CAPABILITY_IAM \
    --stack-name craterdog-bali-environment-us-east-1 \
    --template-url https://s3.amazonaws.com/craterdog-bali-environment-us-east-1/templates/bali-nebula-environment.json 

echo
echo "Done."
