#!/bin/bash

echo
echo "Pushing out the latest version of the cloud formation templates to S3..."
aws --region us-east-1 s3api put-object \
    --bucket craterdog-bali-environment-us-east-1 \
    --key templates/bali-nebula-repository.json \
    --body templates/bali-nebula-repository.json

aws --region us-east-1 s3api put-object \
    --bucket craterdog-bali-environment-us-east-1 \
    --key templates/bali-nebula-html.json \
    --body templates/bali-nebula-html.json

echo
echo "Pushing out the latest version of the style sheets and images to S3..."
aws --region us-west-2 s3api put-object \
    --bucket craterdog-bali-web-us-west-2 \
    --key style/BDN.css \
    --body docs/style/BDN.css

aws --region us-west-2 s3api put-object \
    --bucket craterdog-bali-web-us-west-2 \
    --key images/PoweredByLogo.png \
    --body docs/images/PoweredByLogo.png

echo
echo "Creating the cloud formation stacks..."
#aws --region us-east-1 cloudformation create-stack \
#    --capabilities CAPABILITY_IAM \
#    --stack-name craterdog-bali-repository-us-east-1 \
#    --template-url https://s3.amazonaws.com/craterdog-bali-environment-us-east-1/templates/bali-nebula-repository.json 

aws --region us-east-1 cloudformation create-stack \
    --capabilities CAPABILITY_IAM \
    --stack-name craterdog-bali-html-us-east-1 \
    --template-url https://s3.amazonaws.com/craterdog-bali-environment-us-east-1/templates/bali-nebula-html.json 

echo
echo "Done."
