#!/bin/bash
SCRIPTS=`dirname $0`

echo "Creating the environment bucket..."
aws --region us-east-1 s3api create-bucket \
    --acl private \
    --bucket bali-nebula-environment-us-east-1
echo

echo "Blocking public access to the environment bucket..."
aws --region us-east-1 s3api put-public-access-block \
    --bucket bali-nebula-environment-us-east-1 \
    --public-access-block-configuration BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true
echo

echo "Pushing the latest version of the template out to S3..."
aws --region us-east-1 s3api put-object \
    --bucket bali-nebula-environment-us-east-1 \
    --key templates/environment.json \
    --content-type "application/json" \
    --body templates/environment.json
echo

echo "Creating the cloud formation stack..."
aws --region us-east-1 cloudformation create-stack \
    --capabilities CAPABILITY_IAM \
    --stack-name bali-nebula-environment-us-east-1 \
    --template-url https://s3.amazonaws.com/bali-nebula-environment-us-east-1/templates/environment.json 
echo

echo "Done."
