#!/bin/bash
SCRIPTS=`dirname $0`

echo
echo "Emptying the static bucket..."
${SCRIPTS}/empty-bucket bali-nebula-statics-us-west-2

echo
echo "Pushing out the latest version of the style sheets and images to S3..."
aws --region us-west-2 s3api put-object \
    --bucket bali-nebula-statics-us-west-2 \
    --key styles/BDN.css \
    --content-type "text/css" \
    --body content/styles/BDN.css

aws --region us-west-2 s3api put-object \
    --bucket bali-nebula-statics-us-west-2 \
    --key images/CraterDogLogo.png \
    --content-type "image/png" \
    --body content/images/CraterDogLogo.png

aws --region us-west-2 s3api put-object \
    --bucket bali-nebula-statics-us-west-2 \
    --key images/PoweredByLogo.png \
    --content-type "image/png" \
    --body content/images/PoweredByLogo.png

aws --region us-west-2 s3api put-object \
    --bucket bali-nebula-statics-us-west-2 \
    --key images/favicon.ico \
    --content-type "image/x-icon" \
    --body content/images/favicon.ico

echo
echo "Pushing out the latest version of the cloud formation templates to S3..."
aws --region us-east-1 s3api put-object \
    --bucket bali-nebula-environment-us-east-1 \
    --key templates/static.json \
    --content-type "application/json" \
    --body templates/static.json

aws --region us-east-1 s3api put-object \
    --bucket bali-nebula-environment-us-east-1 \
    --key templates/repository.json \
    --content-type "application/json" \
    --body templates/repository.json

echo
echo "Creating the cloud formation stacks..."
aws --region us-east-1 cloudformation create-stack \
    --capabilities CAPABILITY_IAM \
    --stack-name bali-nebula-static-us-east-1 \
    --template-url https://s3.amazonaws.com/bali-nebula-environment-us-east-1/templates/static.json 

aws --region us-east-1 cloudformation create-stack \
    --capabilities CAPABILITY_IAM \
    --stack-name bali-nebula-repository-us-east-1 \
    --template-url https://s3.amazonaws.com/bali-nebula-environment-us-east-1/templates/repository.json 

echo
echo "Done."
