#!/bin/bash
SCRIPTS=`dirname $0`

echo "Deleting the environment bucket..."
${SCRIPTS}/delete-bucket craterdog-aws-us-east-1

echo "Deleting the logs bucket..."
${SCRIPTS}/delete-bucket craterdog-logs-us-east-1

echo "Deleting the websites bucket..."
${SCRIPTS}/delete-bucket craterdog-websites-us-east-1

echo "Deleting the names bucket..."
${SCRIPTS}/delete-bucket bali-nebula-names-us-east-1

echo "Deleting the drafts bucket..."
${SCRIPTS}/delete-bucket bali-nebula-drafts-us-east-1

echo "Deleting the documents bucket..."
${SCRIPTS}/delete-bucket bali-nebula-documents-us-east-1

echo "Deleting the messages bucket..."
${SCRIPTS}/delete-bucket bali-nebula-messages-us-east-1

echo "Deleting the cloud formation stacks..."
aws --region us-east-1 cloudformation delete-stack \
    --stack-name craterdog-buckets-us-east-1

echo "Done."
