#!/bin/bash
SCRIPTS=`dirname $0`

echo "Emptying the names bucket..."
${SCRIPTS}/empty-bucket bali-nebula-names-us-east-1

echo "Emptying the drafts bucket..."
${SCRIPTS}/empty-bucket bali-nebula-drafts-us-east-1

echo "Emptying the documents bucket..."
${SCRIPTS}/empty-bucket bali-nebula-documents-us-east-1

echo "Emptying the messages bucket..."
${SCRIPTS}/empty-bucket bali-nebula-messages-us-east-1

echo "Emptying the statics bucket..."
${SCRIPTS}/empty-bucket bali-nebula-statics-us-east-1

echo "Deleting the cloud formation stacks..."
aws --region us-east-1 cloudformation delete-stack \
    --stack-name bali-nebula-buckets-us-east-1

echo "Done."
