#!/bin/bash
SCRIPTS=`dirname $0`

echo "Deleting the environment bucket..."
${SCRIPTS}/delete-bucket bali-nebula-environment-us-east-1

echo "Deleting the cloud formation stack..."
aws --region us-east-1 cloudformation delete-stack \
    --stack-name bali-nebula-environment-us-east-1

echo "Done."
