#!/bin/bash
SCRIPTS=`dirname $0`

echo "Emptying the names bucket..."
${SCRIPTS}/empty-bucket bali-nebula-names-us-east-1

echo "Emptying the documents bucket..."
${SCRIPTS}/empty-bucket bali-nebula-documents-us-east-1

echo "Emptying the contracts bucket..."
${SCRIPTS}/empty-bucket bali-nebula-contracts-us-east-1

echo "Emptying the messages bucket..."
${SCRIPTS}/empty-bucket bali-nebula-messages-us-east-1

