#!/bin/bash

echo "Emptying the names bucket..."
./scripts/empty-bucket craterdog-bali-names-us-west-2

echo "Emptying the drafts bucket..."
./scripts/empty-bucket craterdog-bali-drafts-us-west-2

echo "Emptying the documents bucket..."
./scripts/empty-bucket craterdog-bali-documents-us-west-2

echo "Emptying the bags bucket..."
./scripts/empty-bucket craterdog-bali-bags-us-west-2

