#!/bin/bash
SCRIPTS=`dirname $0`
DISTRIBUTION=$1
paths=""

echo "Pushing out the latest style sheets to S3..."
for file in `find content -type f | grep "\.css"`; do
    key=craterdog/${file:8}
    echo "  ${key}";
    aws --region us-east-1 s3api put-object \
        --bucket craterdog-websites-us-east-1 \
        --content-type text/css \
        --key ${key} \
        --body ${file}
    paths="$paths /${file:8}"
done
echo

echo "Pushing out the latest web pages to S3..."
for file in `find content -type f | grep "\.html"`; do
    key=craterdog/${file:8}
    echo "  ${key}";
    aws --region us-east-1 s3api put-object \
        --bucket craterdog-websites-us-east-1 \
        --content-type text/html \
        --key ${key} \
        --body ${file}
    paths="$paths /${file:8}"
done
echo

echo "Pushing out the latest javascript to S3..."
for file in `find content -type f | grep "\.js"`; do
    key=craterdog/${file:8}
    echo "  ${key}";
    aws --region us-east-1 s3api put-object \
        --bucket craterdog-websites-us-east-1 \
        --content-type text/javascript \
        --key ${key} \
        --body ${file}
    paths="$paths /${file:8}"
done
echo

echo "Pushing out the latest JPEG images to S3..."
for file in `find content -type f | grep -E "\.jpe?g"`; do
    key=craterdog/${file:8}
    echo "  ${key}";
    aws --region us-east-1 s3api put-object \
        --bucket craterdog-websites-us-east-1 \
        --content-type image/jpeg \
        --key ${key} \
        --body ${file}
    paths="$paths /${file:8}"
done
echo

echo "Pushing out the latest PNG images to S3..."
for file in `find content -type f | grep "\.png"`; do
    key=craterdog/${file:8}
    echo "  ${key}";
    aws --region us-east-1 s3api put-object \
        --bucket craterdog-websites-us-east-1 \
        --content-type image/png \
        --key ${key} \
        --body ${file}
    paths="$paths /${file:8}"
done
echo

echo "Invalidating the CloudFront cache..."
aws cloudfront create-invalidation \
    --distribution-id $DISTRIBUTION \
    --paths $paths
echo
