#!/bin/bash

echo
echo "Pushing the latest version of the template out to S3..."
aws --region us-east-1 s3api put-object \
    --bucket bali-nebula-environment-us-east-1 \
    --key templates/environment.json \
    --content-type "application/json" \
    --body templates/environment.json

echo
echo "Updating the cloud formation stack..."
aws --region us-east-1 cloudformation update-stack \
    --capabilities CAPABILITY_IAM \
    --stack-name bali-nebula-environment-us-east-1 \
    --template-url https://s3.amazonaws.com/bali-nebula-environment-us-east-1/templates/environment.json 

echo
echo "Done."
