#!/bin/bash

echo
echo "Pushing the latest version of the template out to S3..."
aws --region us-east-1 s3api put-object \
    --bucket craterdog-bali-environment-us-east-1 \
    --key templates/bali-nebula-environment.json \
    --body templates/bali-nebula-environment.json

echo
echo "Updating the cloud formation stack..."
aws --region us-east-1 cloudformation update-stack \
    --capabilities CAPABILITY_IAM \
    --stack-name craterdog-bali-environment-us-east-1 \
    --template-url https://s3.amazonaws.com/craterdog-bali-environment-us-east-1/templates/bali-nebula-environment.json 

echo
echo "Done."
