#!/bin/bash

# copy the latest version of the template out to S3
aws --region us-east-1 s3api put-object \
    --bucket craterdog-bali-nebula-us-east-1 \
    --key templates/BaliNebulaEnvironment.json \
    --body ./templates/BaliNebulaEnvironment.json

# update the environment stack
aws --region us-east-1 cloudformation update-stack \
    --capabilities CAPABILITY_IAM \
    --stack-name craterdog-bali-environment \
    --template-url https://s3.amazonaws.com/craterdog-bali-nebula-us-east-1/templates/BaliNebulaEnvironment.json 

