#!/bin/bash

echo
echo "Pushing the latest version of the template out to S3..."
aws --region us-east-1 s3api put-object \
    --bucket craterdog-bali-environment-us-east-1 \
    --key templates/bali-nebula-buckets.json \
    --content-type "application/json" \
    --body ./templates/bali-nebula-buckets.json

echo
echo "Updating the cloudformation stack..."
aws --region us-west-2 cloudformation update-stack \
    --stack-name craterdog-bali-buckets-us-east-1 \
    --template-url https://s3.amazonaws.com/craterdog-bali-environment-us-east-1/templates/bali-nebula-buckets.json 

echo
echo "Done."
