#!/bin/bash

# copy the latest version of the lambdas out to S3
aws --region us-east-1 s3api put-object \
    --bucket craterdog-bali-nebula-us-east-1 \
    --key lambdas/BaliNebulaRepository.zip \
    --body ../js-bali-nebula-agents/dist/BaliNebulaRepository.zip

# copy the latest version of the template out to S3
aws --region us-east-1 s3api put-object \
    --bucket craterdog-bali-nebula-us-east-1 \
    --key templates/BaliNebulaLambdas.json \
    --body ./templates/BaliNebulaLambdas.json

# update the lambdas stack
aws --region us-west-2 cloudformation update-stack \
    --capabilities CAPABILITY_IAM \
    --stack-name craterdog-bali-lambdas \
    --template-url https://s3.amazonaws.com/craterdog-bali-nebula-us-east-1/templates/BaliNebulaLambdas.json 

