#!/bin/bash
SCRIPTS=`dirname $0`

echo
echo "Pushing out the latest version of the cloud formation templates to S3..."
aws --region us-east-1 s3api put-object \
    --bucket craterdog-aws-us-east-1 \
    --key templates/services.json \
    --content-type "application/json" \
    --body templates/services.json

echo
echo "Updating the cloud formation stacks..."
aws --region us-east-1 cloudformation update-stack \
    --capabilities CAPABILITY_IAM \
    --stack-name bali-nebula-services-us-east-1 \
    --template-url https://s3.amazonaws.com/craterdog-aws-us-east-1/templates/services.json 

echo
echo "Done."
